./PbPb-analysis.sh HiBinUp_   --IsHiBinUp   true
./PbPb-analysis.sh HiBinDown_ --IsHiBinDown true
./PbPb-analysis.sh MuTagged_  --IsMuTagged  false
./PbPb-analysis.sh MuVar0_  --ExtraZWeight 0
./PbPb-analysis.sh MuVar1_  --ExtraZWeight 1
./PbPb-analysis.sh MuVar2_  --ExtraZWeight 2
./PbPb-analysis.sh MuVar3_  --ExtraZWeight 3
./PbPb-analysis.sh MuVar4_  --ExtraZWeight 4
./PbPb-analysis.sh MuVar5_  --ExtraZWeight 5
./PbPb-analysis.sh MuVar6_  --ExtraZWeight 6
./PbPb-analysis.sh MuVar7_  --ExtraZWeight 7
./PbPb-analysis.sh MuVar8_  --ExtraZWeight 8
./PbPb-analysis.sh MuVar9_  --ExtraZWeight 9
./PbPb-analysis.sh MuVar10_  --ExtraZWeight 10
./PbPb-analysis.sh MuVar11_  --ExtraZWeight 11
