./pp-analysis.sh MuTagged_  --IsMuTagged  false
./pp-analysis.sh MuVar0_    --ExtraZWeight 0
./pp-analysis.sh MuVar1_    --ExtraZWeight 1
./pp-analysis.sh MuVar2_    --ExtraZWeight 2
./pp-analysis.sh MuVar3_    --ExtraZWeight 3
./pp-analysis.sh MuVar4_    --ExtraZWeight 4
./pp-analysis.sh MuVar5_    --ExtraZWeight 5
./pp-analysis.sh MuVar6_    --ExtraZWeight 6
./pp-analysis.sh MuVar7_    --ExtraZWeight 7
./pp-analysis.sh MuVar8_    --ExtraZWeight 8
./pp-analysis.sh MuVar9_    --ExtraZWeight 9
./pp-analysis.sh MuVar10_   --ExtraZWeight 10
./pp-analysis.sh MuVar11_   --ExtraZWeight 11
./pp-analysis.sh PU_        --IsPUReject false